### ISSUE TITLE
orb jobs ignores cache_checksum_file and cache_key  

### ISSUE THREAD

**Issue by amitg-dt** [CircleCI-Public/gradle-orb#11]
**Orb Version**
2.2.0

**Describe the bug**
The jobs ignores `cache_checksum_file` and `cache_key` inputs and use the default values.

**To Fix**
Place this variables under the call to the `with_cache` command instead of under `steps/run` which refers only to the scope of the `./gradew` shell command.

**Comment by dsvensson** [comment]
This is probably because yaml uses wrong indentation here:

https://github.com/CircleCI-Public/gradle-orb/blob/master/src/jobs/test.yml#L40-L41

**Comment by dsvensson** [comment]
Another issue with the cache is that it combines both dependencies cache and gradle wrapper in one cache blob. It should be better to have them separate as dependencies has a higher volatility than gradle wrapper in most projects.

**Comment by Jaryt** [comment]
Closing since we merged #13 which fixes this :)
