### ISSUE TITLE
Split wrapper and dependencies cache

### ISSUE THREAD

**Issue by dsvensson** [CircleCI-Public/gradle-orb#12]
Over a couple of months it's more likely that dependencies change than the gradle wrapper changes. If there's not any significant win of having just one cache entry, I would expect most users would gain from having separate caches.

**Comment by Jaryt** [comment]
This is a good idea. Will look into doing this 👍

**Comment by Jaryt** [comment]
@dsvensson Please feel free to take a look at that implementation and let me know if you have any opinions! 🎉

**Comment by Jaryt** [comment]
Merged in #15, since it's a breaking version change I'd like to find some more features or fixes to package with this.
