### ISSUE TITLE
Improve cache key used for by `with_cache` for caching gradle distributions

### ISSUE THREAD

**Issue by jamesbassett** [CircleCI-Public/gradle-orb#18]
**Is your feature request related to a problem? Please describe.**
The current implementation of `with_cache` uses the gradle wrapper script (`gradlew`) to form the cache key for caching gradle distributions (in the `~/.gradlew/wrapper` directory). It's my experience that the wrapper script is only updated as required, and is not tied to a specific version of Gradle, so is not a good candidate for a cache key.

**Describe the solution you'd like**
I think it would make more sense to use `gradle/wrapper/gradle-wrapper.properties` as it is OS-independent and it more accurately reflects the Gradle distro being used by the build.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Jaryt** [comment]
Agreed! However, I believe we're moving towards a standard of using the command to pull the version and dump that into a tmp file. (see: https://github.com/CircleCI-Public/python-orb/commit/918ff5bef4cef390aaf3c283d28a96f13d9a0c21) It'll be simple enough to regex the value out, reducing the odds of cache changes occurring with those other values.

**Comment by jamesbassett** [comment]
That might be a challenge - I don't think the wrapper script will give you that info without downloading the actual distribution (which defeats the purpose of the cache).

I think hashing the `gradle-wrapper.properties` file is probably the cleanest solution - the only time it changes is when you upgrade the gradle version. Interestingly that file already supports (opt-in) storing the [hash of the distro](https://docs.gradle.org/current/userguide/gradle_wrapper.html#configuring_checksum_verification) (for verifying the download)

**Comment by Jaryt** [comment]
> That might be a challenge - I don't think the wrapper script will give you that info without downloading the actual distribution (which defeats the purpose of the cache).

Good point! I just tested and am able to confirm that the wrapper does not download any binaries when using the "--version" flag

**Comment by ryanbourdais** [comment]
Hi @jamesbassett it seems you and jaryt came to the conclusion that caching `gradle-wrapper.properties` as the default rather than `gradlew` I'm assuming as the arg for `wrapper_checksum_file`  in the `with_cache` command, is that correct?

**Comment by skjolber** [comment]
@jamesbassett yes, that is correct.

**Comment by skjolber** [comment]
@ryanbourdais I cannot think of a use-case where `wrapper_checksum_file` is not the properties file, so one could argue that a parameter is just dead weight (and should be removed).

**Comment by jamesbassett** [comment]
Sorry for the slow reply, I think @skjolber is correct and the parameter is redundant (you should safely be able to hardcode it to `gradle-wrapper.properties`.

The only exception I can think of is if somebody was using a custom gradle distribution from a URL that didn't specify the version. Obviously that's not great from a reproducible build point of view, so it's probably not a use case you'd want to support.

**Comment by ryanbourdais** [comment]
@skjolber @jamesbassett I do agree, I can't see any cases where the wrapper file will change, so I'll open a new PR to remove that parameter and default it to `gradle/wrapper/gradle-wrapper.properties`

**Comment by ryanbourdais** [comment]
#27 was merged and fixes this issue so I am now closing this issue.
