### ISSUE TITLE
Add support for saving test artifacts on the workspace.

### ISSUE THREAD

**Issue by felippemr** [CircleCI-Public/gradle-orb#19]
**Is your feature request related to a problem? Please describe.**
I need to run sonarqube after my tests run. The problem is that they are different jobs in the CI and sonarqube needs the coverage report generated by jacoco so that it can analyze my PR. Downloading the stored artifacts using the circle ci job URL does not work because the job number is dynamic. The best option is saving the jacoco artifacts on the workspace and loading it on the next job.

**Describe the solution you'd like**
I need to reuse test artifacts accross jobs without relying on the stored artifacts.

**Describe alternatives you've considered**
I would like to either be able to add extra steps to the test/run jobs or to have an option of persisting the test artifacts to the workspace. This is a much better option than using the stored artifacts since I won't have to manually download them.

**Additional context**
Once we agree on an implementation I can work on this.

**Comment by Jaryt** [comment]
Hi @felippemr! You should be able to achieve exactly this with pre and post steps: https://circleci.com/docs/configuration-reference/#pre-steps-and-post-steps 
As you described, utilize post steps for gradle/test to include the persist to workspace, and pre-steps with attach workspace for the sonarqube job. 

Please let me know if you require any further assistance with this!
