### ISSUE TITLE
app_src_directory parameter vs file / path parameters

### ISSUE THREAD

**Issue by skjolber** [CircleCI-Public/gradle-orb#26]
The run and test jobs currently have a `app_src_directory` parameter. If this parameter is used, one also has to use the parameters `deps_checksum_file`, `wrapper_checksum_file`, `test_results_path` and `reports_path` to get it all pointing to the right paths. 

Would it be possible to make it so that the `app_src_directory` is prepended to the other parameters? In other words so that the `app_src_directory` parameter can be used alone?

**Comment by skjolber** [comment]
Also there is a typo in the `app_src_directory` description (maven -> gradle)

**Comment by ryanbourdais** [comment]
Hi @skjolber , the issue with that is that there isnt much logic we can use outside of our scripts. I could tack it on the the front such as ` deps_checksum_file: << parameters.app_src_directory >>/<< parameters.deps_checksum_file >>` but then we would run into issues where it would output as `sample_app/build.gradle.kts, settings.gradle.kts, libs.versions.toml
` if you had more than 1 dependency file to cache. I will definitely go and fix `app_src_directory` in a small PR shortly though, thank you for the heads up
