### ISSUE TITLE
Support `build.gradle.kts` as the gradle file name without additional configuration

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/gradle-orb#3]
**Orb Version**
2.0

**Describe the bug**
Porting issue from old repo: https://github.com/CircleCI-Public/circleci-orbs/issues/180
reporter: @moormaan

**Expected behavior**
If Gradle Kotlin DSL is used, with_cache will not be able to generate the key, since gradle file will be named build.gradle.kts. This file name should be used as an alternative to build.gradle without additional configuration because Kotlin DSL is an official part of Gradle.

---

Suggestion from @iynere 

> @moormaan great point. would you like to submit a small PR to fix?
> 
> my suggestion: instead of hardcodinig `build.gradle`, create a `cache-key-filename` parameter with a default value of `build.gradle`, & replace `find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed`
> 
> with `find . -name '<<parameters.cache-key-filename>>' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed`:
> 
> https://github.com/CircleCI-Public/circleci-orbs/blob/staging/src/gradle/orb.yml#L94

**Comment by petergphillips** [comment]
I've created https://github.com/CircleCI-Public/gradle-orb/pull/6 to fix and allow a `cache_checksum_file` to be passed in to override the default `build.gradle`.

I've created the PR against the `Alpha` branch as per the README, but this branch is out of date with respect to `master`, hence the conflicts and extra commits.
