### ISSUE TITLE
Collect all Reports in project

### ISSUE THREAD

**Issue by robertfmurdock** [CircleCI-Public/gradle-orb#4]
Currently, the collect_test_results command does not search through a multiproject and collect the reports.

It'd be excellent for it to collect reports and put them in the target directory under the module name.

**Comment by Jaryt** [comment]
Hi @robertfmurdock ! I'm investigating adding this into the gradle orb. I have some clarifying questions that would be helpful in making sure I'm on the same page: By reports, do you mean test reports, or the test results xml files? I can see how both would be useful, and that it'd make sense for them to be implemented within the same patch fix.

**Comment by Jaryt** [comment]
@robertfmurdock touching base on another question I had. Would this be a parallel (monorepo like) project structure, or submodule? 

Again... thinking the answer might just be 'both' but I'm more familiar with the submodule structure.

**Comment by KyleTryon** [comment]
Hello,

There have been updates to this orb since this issue was opened and it has been some time since the last contact. We are closing this issue for the time being but please let us know if there are any issues with the latest version of the orb.
